spring:
  datasource:
    url: jdbc:mysql://mysql-207432-0.cloudclusters.net:10047/medpointdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: mudita
    password: EMM@RESCUe12

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    com.medpoint: INFO