spring:
  application:
    name: medpoint-backend
  profiles:
    active: dev
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB

app:
  upload:
    dir: uploads
  base-url: http://localhost:8080/api
  dev-mode: false


server:
  port: 8080
  servlet:
    context-path: /api

jwt:
  secret: medpoint-super-secret-key-must-be-at-least-256-bits-long-change-in-prod
  expiration-ms: 86400000

logging:
  level:
    com.medpoint: DEBUG
    org.springframework.security: WARN

---
spring:
  config:
    activate:
      on-profile: dev
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-app-password
    properties:
      mail.smtp.starttls.enable: true
  datasource:
    url: jdbc:mysql://localhost:3306/medpointdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: EMMARESCUE
app:
  dev-mode: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

---
#spring:
#  config:
#    activate:
#      on-profile: prod
#  datasource:
#    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:medpointdb}?useSSL=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: ${DB_USERNAME:medpoint}
#    password: ${DB_PASSWORD:medpoint}
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
